### ISSUE TITLE
Misleading README

### ISSUE THREAD

**Issue by mgartner** [cainus/node-coveralls#83]
While integrating my project with coveralls, I tried following the README, but the instructions are very confusing. The commands listed do not mention to what file they should be added, or what exactly needs to be done.

Most of all, this wording is very confusing:

> This library currently supports travis-ci with no extra effort beyond that, but if you're using a different build system, there are a few environment variables that are necessary:

In actuality, you have to edit both your package.json and .travis.yml to make everything work correctly. Restructuring the README to more of a step-by-step guide would be very useful, i.e.:

1. Install coveralls, mochs, istanbul, etc.
2. Add a new script to package.json with the test command.
3. Edit .travis.yml to run the script instead of `npm test`.

I'd be happy to help rewrite some of it, if you agree.

**Comment by cainus** [comment]
Well you have to get travis to run the script, that's for sure.  That's why there are the examples on lines to run for different set-ups.

Your line #1 assumes a lot of things that aren't necessarily the case.  As you can see from the README there are a bunch of different possibilities for #1.

I generally just have `npm test

**Comment by mgartner** [comment]
I agree it doesn't need to be for a specific setup, but no where does it mention that you need to have travis run those commands, or any setup you need to do in .travis.yml or other CI script. Just confusing looking at the commands and not knowing where to put them.

**Comment by cainus** [comment]
Hmmm on second look, the quote you originally mentioned is a bit out of context (emphasis mine):

>This library currently supports travis-ci with no extra effort beyond **that**, but if you're using a different build system, there are a few environment variables that are necessary:

The two previous paragraphs explain what *that* means, which I think is a the general overview of how to run the script that you were expecting (and we've got a number of specific examples below that).

I'm willing to take a PR that makes that clearer, but it's definitely less clear if you don't notice the previous two paragraphs.  Also, If I could make it clearer myself, I would've already done so, so I'm totally reliant on input from others.

**Comment by mgartner** [comment]
Ahh, I understand better with the emphasis on what that is. I put up a PR to try to make it more clear, but looking back it's not too confusing, I was just skimming over it too much.

:+1: Thanks for the clarification.

**Comment by mgartner** [comment]
Closed by #84.
